%% ================================================================
% RMIST-Net Synthetic Training Data Generator (Fixed Mask Version)
% ================================================================
% This script generates complex-valued training pairs (GT image, sparse echo)
% for the RMIST-Net model, following Wang et al., IEEE TGRS 2022.
%
%  - Each ground-truth image α_gt ∈ ℂ^(H×W) is a sparse complex scene
%    with randomly distributed point targets (amplitude + random phase).
%
%  - Echo is generated by the RM forward model:
%        S_full = IFFT2( FFT2(α_gt) .* Phi_r )
%
%  - A SINGLE fixed sampling mask "Train_Mask" is generated ONCE and
%    applied to ALL samples:
%        S_sparse = S_full .* Train_Mask
%
%  - Complex AWGN is added with target SNR in dB:
%        S_cplx = S_sparse + noise
%
%  - The script saves:
%       Train_GT    : [H x W x NUM_PAIRS] complex ground truth images
%       Train_Echo  : [H x W x NUM_PAIRS] complex echoes (masked + noisy)
%       Train_Mask  : [H x W] sampling mask (same for all samples)
%       H, W, R, SR, fc, c : parameters
%
% ================================================================

clear; clc; close all;

%% --- System and Imaging Parameters (similar to paper) ---
H  = 512;          % Image height  (z-direction, rows)
W  = 512;          % Image width   (x-direction, cols)
R  = 0.5;          % Range distance to slice (meters)
fc = 78.3e9;       % Carrier frequency (Hz)
c  = 3e8;          % Speed of light (m/s)

%% --- Training Data Parameters ---
NUM_PAIRS = 700;  % number of (GT, Echo) pairs (paper uses ~1000)
SR        = 0.7;   % sampling rate (0–1), e.g. 0.7 means 70% samples kept
SNR_dB    = 20;    % SNR for AWGN noise (dB)

fprintf('Generating RMIST-Net training data with:\n');
fprintf('  H = %d, W = %d, NUM_PAIRS = %d, SR = %.2f, SNR = %d dB\n', ...
    H, W, NUM_PAIRS, SR, SNR_dB);

%% --- Precompute RM Kernel Phi_r (same for all samples at range R) ---
% Coordinate in image domain (arbitrary scaling, consistent with kernel)
x = linspace(-W/2, W/2, W);   % horizontal (x)
z = linspace(-H/2, H/2, H);   % vertical   (z)
[~, ~] = meshgrid(x, z);      % not used directly, but shown for clarity

K0 = 2*pi*fc/c;

% Spatial-frequency sampling (kx, kz)
dx = x(2) - x(1);
dz = z(2) - z(1);
dkx = 2*pi / (W * dx);
dkz = 2*pi / (H * dz);

kx = linspace(-W/2, W/2, W) * dkx;
kz = linspace(-H/2, H/2, H) * dkz;
[Kx, Kz] = meshgrid(kx, kz);   % size [H x W]

K_sq    = Kx.^2 + Kz.^2;
K_check = 4*K0^2 - K_sq;
Ky      = sqrt(max(0, K_check));         % clamp evanescent region

% RM kernel φ_r = (1/ky) * exp(-j*ky*R)
Phi_r = (1 ./ Ky) .* exp(-1i * Ky * R);
Phi_r(Ky == 0) = 0;   % handle singularity safely


save('Phi_r.mat', 'Phi_r');
fprintf('RM kernel Phi_r computed.\n');

% ---------------------------------------------

R = 185*1e-3;
% RM kernel φ_r_drag = (ky) * exp(j*ky*R)
Phi_r_dag = Ky.*exp(1i*Ky*R);

save('Phi_r_dag.mat','Phi_r_dag');
% ---------------------------------------------

%% --- Create ONE fixed sampling mask (Train_Mask) ---
Train_Mask = rand(H, W) < SR;   % Bernoulli mask with sampling rate SR

fprintf('Fixed sampling mask generated (SR ≈ %.2f).\n', SR);

%% --- Allocate storage for training data ---
Train_GT   = complex(zeros(H, W, NUM_PAIRS));
Train_Echo = complex(zeros(H, W, NUM_PAIRS));

%% --- Main Loop: Generate Training Pairs ---
for i = 1:NUM_PAIRS
    if mod(i, 100) == 0
        fprintf('  Generating pair %4d / %4d\n', i, NUM_PAIRS);
    end

    [alpha_gt, S_cplx] = generate_rmist_data_slice(H, W, Phi_r, Train_Mask, SNR_dB);

    Train_GT(:,:,i)   = alpha_gt;
    Train_Echo(:,:,i) = S_cplx;
end

fprintf('All %d pairs generated.\n', NUM_PAIRS);

%% --- Save to .mat file ---
out_file = 'RMIST_Training_Data_paper.mat';
save(out_file, 'Train_GT', 'Train_Echo', ...
   'H', 'W', 'R', 'SR', 'fc', 'c', '-v7.3');

%% --- Quick Visualization of One Sample ---
sample_index = 1;
alpha_gt = Train_GT(:,:,sample_index);
S_cplx   = Train_Echo(:,:,sample_index);

max_amp_gt   = max(abs(alpha_gt(:)));
max_amp_echo = max(abs(S_cplx(:)));

figure('Position', [100, 100, 1200, 500]);

% 1) Ground-Truth magnitude
subplot(1, 3, 1);
imagesc(abs(alpha_gt), [0, max_amp_gt]);
axis image off;
colormap(gca, 'jet');
colorbar;
title(sprintf('GT |α| (sample %d)', sample_index));

% 2) Echo magnitude in dB
subplot(1, 3, 2);
S_mag_dB = 20*log10(abs(S_cplx) / max_amp_echo);
imagesc(S_mag_dB, [max(S_mag_dB(:))-40, max(S_mag_dB(:))]);
axis image off;
colormap(gca, 'gray');
colorbar;
title('Echo |S| (dB, masked + noisy)');

% 3) Sampling Mask
subplot(1, 3, 3);
imagesc(Train_Mask);
axis image off;
colormap(gca, 'gray');
colorbar;
title('Fixed Sampling Mask');

fprintf('Visualization complete.\n');

%% ===================== Local Function ===================== %%
function [alpha_gt, S_cplx] = generate_rmist_data_slice(H, W, Phi_r, Mask, SNR_dB)
% generate_rmist_data_slice
%   Generates ONE (GT, Echo) pair for RMIST-Net training, given:
%     - H, W   : image size
%     - Phi_r  : RM kernel (H x W) precomputed
%     - Mask   : fixed sampling mask (H x W)
%     - SNR_dB : SNR for complex AWGN
%
%   Output:
%     alpha_gt : [H x W] complex ground-truth image
%     S_cplx   : [H x W] complex echo (masked + AWGN)

    % --- 1. Generate sparse complex GT image (random point targets) ---
    alpha_gt = complex(zeros(H, W));

    % Number of point targets (you can adjust the range)
    num_targets = randi([50 150]);   % e.g., between 50 and 150 point scatterers

    for k = 1:num_targets
        % Random (row, col) position
        r = randi([1, H]);  % row (z)
        c = randi([1, W]);  % col (x)

        % Random amplitude and phase
        amplitude = 1 + rand();       % amplitude in [1, 2]
        phase     = 2*pi*rand();      % phase in [0, 2π)

        alpha_gt(r, c) = amplitude * exp(1i * phase);
    end

    % Normalize so that max |α| = 1
    maxval = max(abs(alpha_gt(:)));
    if maxval > 0
        alpha_gt = alpha_gt / maxval;
    end

    % --- 2. Forward RM model: S_full = RM(alpha_gt) ---
    %      S_full = IFFT2( FFT2(alpha_gt) .* Phi_r )
    S_full = ifft2( fft2(alpha_gt) .* Phi_r );

    % --- 3. Apply fixed mask ---
    S_sparse = S_full .* Mask;

    % --- 4. Add complex AWGN noise with target SNR ---
    % Using Communication Toolbox "awgn" with 'measured' option
    S_cplx = awgn(S_sparse, SNR_dB, 'measured');

end

%% ----- WE CREATING α=IFT2(FT2(S)⊙ϕr†​)≡RM†(S)
clc; clear; close all; 
data1 = load('test_echo.mat');
data2 = load('Phi_r.mat'); 
data3 = load('Phi_r_dag.mat'); 
%data4 = load('sar_image.mat');
data4 = load('trueImage_complex_RMA_RMIST_512.mat');


Phi_r     = data2.Phi_r;        % φ_r   (forward RM kernel)
Phi_r_dag = data3.Phi_r_dag;    % φ_r^† (adjoint RM kernel)

% ---------- Adjoint: α̂ = RM†(S) ----------
S   = double(data1.sarData);    % echo S
F_S = fft2(S);                  % FT2(S)
A_temp   = F_S .* Phi_r_dag;    % ⊙ φ_r^†
alpha_hat = ifft2(A_temp);      % α̂ = IFT2( FT2(S) ⊙ φ_r^† )


% ---------- Forward: Ŝ = RM(A) ----------
A   = double(data4.trueImage_complex);  % treat this as α
F_A = fft2(A);                       % FT2(α)
S_temp = F_A .* Phi_r_dag;              % ⊙ φ_r
S_hat  = ifft2(S_temp);             % Ŝ = IFT2( FT2(α) ⊙ φ_r )
% ------------------------------------
save('S_hat_knife.mat', 'S_hat');

fprintf('✅ Saved forward output to S_hat.mat (complex, size %dx%d)\n', size(S_hat,1), size(S_hat,2));

%--------------------------------------


% ---------- Apply adjoint to S_hat: α_back = RM†(Ŝ) ----------
F_S_hat  = fft2(S_hat);                 % FT2(Ŝ)
A_back   = ifft2(F_S_hat .* Phi_r_dag); % α_back = IFT2( FT2(Ŝ) ⊙ φ_r^† )

% ---------- Plots ----------
figure('Position',[100 100 1600 600])
subplot(2,3,1);
imagesc(abs(A)); axis image off; colormap jet; colorbar;
title('|α| (Original SAR image)');

subplot(2,3,2);
imagesc(abs(S_hat)); axis image off; colormap jet; colorbar;
title('|Ŝ| = |RM(α)|');

subplot(2,3,3);
imagesc(abs(A_back)); axis image off; colormap jet; colorbar;
title('|A_{back}| = |RM†(RM(α))|');

% % -------------------------------------------------
% % 1. Adjoint (RM†)
% % -------------------------------------------------
% figure('Position', [100 100 1600 500]);
% subplot(1,3,1);
% imagesc(abs(S)); axis image off; colormap jet; colorbar;
% title('|S| (Echo Input)');
% 
% subplot(1,3,2);
% imagesc(abs(alpha_hat)); axis image off; colormap jet; colorbar;
% title('|α̂| = |RM†(S)|');
% 
% subplot(1,3,3);
% imagesc(angle(alpha_hat)); axis image off; colormap hsv; colorbar;
% title('Phase(α̂)');
% 
% sgtitle('Adjoint Operation (α̂ = RM†(S))');
% 
% % -------------------------------------------------
% % 2. Forward (RM)
% % -------------------------------------------------
% figure('Position', [100 650 1600 500]);
% subplot(1,3,1);
% imagesc(abs(A)); axis image off; colormap jet; colorbar;
% title('|α| (SAR Image Input)');
% 
% subplot(1,3,2);
% imagesc(abs(S_hat)); axis image off; colormap jet; colorbar;
% title('|Ŝ| = |RM(α)|');
% 
% subplot(1,3,3);
% imagesc(abs(S_hat - S)); axis image off; colormap jet; colorbar;
% title('|Difference| = |RM(α) - S|');
% 
% sgtitle('Forward Operation (Ŝ = RM(α))');
